### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rschenck** [raphael-group/calder#1]
Hi guys. Great tool. I look forward to giving it a try. I'm currently receiving an error that may need addressing:

```bash
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 11
	at ILPResult.prettyPrint(ILPResult.java:285)
	at ILPResult.toString(ILPResult.java:147)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at Main.main(Main.java:119)
	at JarMain.main(JarMain.java:176)
```

For reproducibility, I'm on Mac OS X and using Gurobi 8.1.1 with java 1.8.0_181.

My input command is:
```bash
 java -jar calder.jar -i input.txt -o calderOutput/ --print-graph
```
Here is an example of the data [input.txt](https://github.com/raphael-group/calder/files/3257039/input.txt)

I seem to get this error quite frequently with various inputs.

**Comment by bend87** [comment]
Thanks for the message - are you using the current version of CALDER? (most recent commit to master)

**Comment by rschenck** [comment]
Yes I am. It was cloned yesterday afternoon and I see the last commit was 6 days ago.

**Comment by bend87** [comment]
Try the current version. I suspect your error had to do with not including a leading "empty" entry in the header of the TSV input file, and added some logic so that parsing is no longer sensitive to this distinction.

**Comment by rschenck** [comment]
For that example input I still receive an error when the `-r` option is used with the latest push:
```bash
Removed empty entry at the start of the header line.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 92
	at Instance.constructInstance(Instance.java:148)
	at Instance.readInstanceFromFile(Instance.java:318)
	at Instance.fromFile(Instance.java:166)
	at Main.main(Main.java:67)
	at JarMain.main(JarMain.java:176)
```

Without the `-r` option I am not receiving the error for the above input. However, with a few other samples that I'm running calder on I'm getting an java.lang.ArrayIndexOutOfBoundsException still. Here is what that looks like:

```bash
Removed empty entry at the start of the header line.
WARNING: found mutation with abnormally high frequency (confidence interval lower bound > 0.5).
Mutation 12:54352727 had original interval [0.5220577508939629, 0.5430002833513328], truncating to [0.49999, 0.5].
Mutation 12:56498846 had original interval [0.5220577508939629, 0.5430002833513328], truncating to [0.49999, 0.5].
Mutation 16:16228258 had original interval [0.5095935954440146, 0.5289152558530131], truncating to [0.49999, 0.5].
Mutation 16:20814168 had original interval [0.5095935954440146, 0.5289152558530131], truncating to [0.49999, 0.5].
Mutation 16:56864491 had original interval [0.5849978055305991, 0.6063031376535241], truncating to [0.49999, 0.5].
Mutation 16:58201687 had original interval [0.5849978055305991, 0.6063031376535241], truncating to [0.49999, 0.5].
Mutation 17:26961902 had original interval [0.5275822841167846, 0.5448341515851554], truncating to [0.49999, 0.5].
Mutation 17:35300346 had original interval [0.5275822841167846, 0.5448341515851554], truncating to [0.49999, 0.5].
Mutation 18:21723133 had original interval [0.6553361728610977, 0.6709681387285842], truncating to [0.49999, 0.5].
Mutation 18:34359430 had original interval [0.6553361728610977, 0.6709681387285842], truncating to [0.49999, 0.5].
Mutation 19:9938669 had original interval [0.5083154365761128, 0.5286272879642369], truncating to [0.49999, 0.5].
Mutation 2:120020728 had original interval [0.5083154365761128, 0.5286272879642369], truncating to [0.49999, 0.5].
Mutation 20:44469465 had original interval [0.579978717331135, 0.6002945474412791], truncating to [0.49999, 0.5].
Mutation 20:4879928 had original interval [0.579978717331135, 0.6002945474412791], truncating to [0.49999, 0.5].
Mutation 4:5499500 had original interval [0.6132676879771344, 0.6348777361021687], truncating to [0.49999, 0.5].
Mutation 4:5500772 had original interval [0.6132676879771344, 0.6348777361021687], truncating to [0.49999, 0.5].
Mutation 5:171534797 had original interval [0.6175233281346837, 0.6345897037966349], truncating to [0.49999, 0.5].
Mutation 5:30564894 had original interval [0.6175233281346837, 0.6345897037966349], truncating to [0.49999, 0.5].
Mutation 6:39328304 had original interval [0.6913826709502031, 0.7129571827522508], truncating to [0.49999, 0.5].
Mutation 6:76628640 had original interval [0.6913826709502031, 0.7129571827522508], truncating to [0.49999, 0.5].
Mutation 8:108297036 had original interval [0.5021394923188388, 0.5222882792813186], truncating to [0.49999, 0.5].
Mutation 8:140797066 had original interval [0.5021394923188388, 0.5222882792813186], truncating to [0.49999, 0.5].
Mutation 9:130289581 had original interval [0.5890674230592571, 0.6071967643893459], truncating to [0.49999, 0.5].
Mutation 9:35869820 had original interval [0.5890674230592571, 0.6071967643893459], truncating to [0.49999, 0.5].
Mutation X:30254075 had original interval [0.5841014073942022, 0.6139862362044884], truncating to [0.49999, 0.5].
Mutation X:39515527 had original interval [0.5841014073942022, 0.6139862362044884], truncating to [0.49999, 0.5].
Mutation X:70518334 had original interval [0.5941819759800924, 0.611461813534825], truncating to [0.49999, 0.5].
Mutation X:95981565 had original interval [0.5941819759800924, 0.611461813534825], truncating to [0.49999, 0.5].
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 188
	at Instance.constructInstance(Instance.java:99)
	at Instance.readInstanceFromFile(Instance.java:318)
	at Instance.fromFile(Instance.java:166)
	at Main.main(Main.java:67)
	at JarMain.main(JarMain.java:176)
```

**Comment by rschenck** [comment]
I should note for the last error, I receive a different error when using the `-r` option:
```bash
Removed empty entry at the start of the header line.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 188
	at Instance.lambda$constructInstance$0(Instance.java:151)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at Instance.constructInstance(Instance.java:151)
	at Instance.readInstanceFromFile(Instance.java:318)
	at Instance.fromFile(Instance.java:166)
	at Main.main(Main.java:67)
	at JarMain.main(JarMain.java:176)
```

**Comment by bend87** [comment]
I was unable to reproduce your errors - I suspect that you may have some improperly formatted input files (i.e., the length of your header may not always match the length of the subsequent rows). The newest version should more clearly indicate which part of the parsing is having an issue.

**Comment by rschenck** [comment]
Great! Thank you. I was attempting with and without clustering. If it helps, with clustering appears to work fine. Without it and this error is thrown. Thanks for the attention on this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
